import { expect, describe, test } from '@jest/globals'
import Room from './classes/Room'

describe('day06', () => {
  test('Part 1', () => {
    const data = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`
    const room = new Room(data)
    expect(room.Walk()).toBe(41)
  })

  test('Part 2', () => {
    const data = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`
    expect(Room.findLoops(data)).toBe(6)
  })

})